/**
 * Demonym → ISO 3166-1 alpha-2 country code.
 *
 * Keyed by the exact strings in `NATIONALITIES` (`lib/nationalities.ts`),
 * which is what `PayrollProfile.nationality` stores. Pure data, no
 * `server-only` — same as the list it mirrors.
 *
 * Why it exists: the LHDN CP39 / e-Data PCB detail record carries a
 * 2-character country code (positions 109-110) beside a foreign
 * employee's passport number. Nothing on the profile held one, so the
 * field went out blank for every foreign employee. The nationality
 * dropdown already names the country, so this derives the code instead
 * of adding a field the admin would have to fill twice.
 *
 * An unmapped or missing nationality returns "" and the renderer leaves
 * the field blank — the behaviour before this map existed.
 *
 * LHDN publishes its own country-code table. It follows ISO alpha-2 for
 * every case checked so far, but a rejection naming the country code is
 * a sign to verify a specific entry against their list rather than to
 * assume this map is right.
 */
export const NATIONALITY_TO_COUNTRY_CODE: Readonly<Record<string, string>> = {
  Malaysian: "MY",
  Afghan: "AF",
  Albanian: "AL",
  Algerian: "DZ",
  American: "US",
  Andorran: "AD",
  Angolan: "AO",
  Argentine: "AR",
  Armenian: "AM",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bahamian: "BS",
  Bahraini: "BH",
  Bangladeshi: "BD",
  Barbadian: "BB",
  Belarusian: "BY",
  Belgian: "BE",
  Belizean: "BZ",
  Beninese: "BJ",
  Bhutanese: "BT",
  Bolivian: "BO",
  Bosnian: "BA",
  Botswanan: "BW",
  Brazilian: "BR",
  British: "GB",
  Bruneian: "BN",
  Bulgarian: "BG",
  Burkinabe: "BF",
  Burmese: "MM",
  Burundian: "BI",
  Cambodian: "KH",
  Cameroonian: "CM",
  Canadian: "CA",
  "Cape Verdean": "CV",
  "Central African": "CF",
  Chadian: "TD",
  Chilean: "CL",
  Chinese: "CN",
  Colombian: "CO",
  Comoran: "KM",
  Congolese: "CG",
  "Costa Rican": "CR",
  Croatian: "HR",
  Cuban: "CU",
  Cypriot: "CY",
  Czech: "CZ",
  Danish: "DK",
  Djiboutian: "DJ",
  Dominican: "DO",
  Dutch: "NL",
  "East Timorese": "TL",
  Ecuadorean: "EC",
  Egyptian: "EG",
  Emirati: "AE",
  "Equatorial Guinean": "GQ",
  Eritrean: "ER",
  Estonian: "EE",
  Ethiopian: "ET",
  Fijian: "FJ",
  Filipino: "PH",
  Finnish: "FI",
  French: "FR",
  Gabonese: "GA",
  Gambian: "GM",
  Georgian: "GE",
  German: "DE",
  Ghanaian: "GH",
  Greek: "GR",
  Grenadian: "GD",
  Guatemalan: "GT",
  Guinean: "GN",
  Guyanese: "GY",
  Haitian: "HT",
  Honduran: "HN",
  "Hong Konger": "HK",
  Hungarian: "HU",
  Icelandic: "IS",
  Indian: "IN",
  Indonesian: "ID",
  Iranian: "IR",
  Iraqi: "IQ",
  Irish: "IE",
  Israeli: "IL",
  Italian: "IT",
  Ivorian: "CI",
  Jamaican: "JM",
  Japanese: "JP",
  Jordanian: "JO",
  Kazakh: "KZ",
  Kenyan: "KE",
  Kuwaiti: "KW",
  Kyrgyz: "KG",
  Lao: "LA",
  Latvian: "LV",
  Lebanese: "LB",
  Liberian: "LR",
  Libyan: "LY",
  Liechtensteiner: "LI",
  Lithuanian: "LT",
  Luxembourger: "LU",
  Macanese: "MO",
  Macedonian: "MK",
  Malagasy: "MG",
  Malawian: "MW",
  Maldivian: "MV",
  Malian: "ML",
  Maltese: "MT",
  Mauritanian: "MR",
  Mauritian: "MU",
  Mexican: "MX",
  Moldovan: "MD",
  Monegasque: "MC",
  Mongolian: "MN",
  Montenegrin: "ME",
  Moroccan: "MA",
  Mozambican: "MZ",
  Namibian: "NA",
  Nepali: "NP",
  "New Zealander": "NZ",
  Nicaraguan: "NI",
  Nigerian: "NG",
  Nigerien: "NE",
  "North Korean": "KP",
  Norwegian: "NO",
  Omani: "OM",
  Pakistani: "PK",
  Palestinian: "PS",
  Panamanian: "PA",
  "Papua New Guinean": "PG",
  Paraguayan: "PY",
  Peruvian: "PE",
  Polish: "PL",
  Portuguese: "PT",
  Qatari: "QA",
  Romanian: "RO",
  Russian: "RU",
  Rwandan: "RW",
  Salvadoran: "SV",
  Samoan: "WS",
  Saudi: "SA",
  Senegalese: "SN",
  Serbian: "RS",
  Seychellois: "SC",
  "Sierra Leonean": "SL",
  Singaporean: "SG",
  Slovak: "SK",
  Slovenian: "SI",
  Somali: "SO",
  "South African": "ZA",
  "South Korean": "KR",
  "South Sudanese": "SS",
  Spanish: "ES",
  "Sri Lankan": "LK",
  Sudanese: "SD",
  Surinamese: "SR",
  Swazi: "SZ",
  Swedish: "SE",
  Swiss: "CH",
  Syrian: "SY",
  Taiwanese: "TW",
  Tajik: "TJ",
  Tanzanian: "TZ",
  Thai: "TH",
  Togolese: "TG",
  Tongan: "TO",
  Trinidadian: "TT",
  Tunisian: "TN",
  Turkish: "TR",
  Turkmen: "TM",
  Ugandan: "UG",
  Ukrainian: "UA",
  Uruguayan: "UY",
  Uzbek: "UZ",
  Venezuelan: "VE",
  Vietnamese: "VN",
  Yemeni: "YE",
  Zambian: "ZM",
  Zimbabwean: "ZW",
}

/**
 * Country code for a stored nationality string, or "" when it isn't one
 * we recognise. Case- and whitespace-tolerant, because legacy rows hold
 * free text typed before the dropdown existed.
 */
export function nationalityToCountryCode(
  nationality: string | null | undefined,
): string {
  const value = (nationality ?? "").trim()
  if (value.length === 0) return ""
  const direct = NATIONALITY_TO_COUNTRY_CODE[value]
  if (direct) return direct
  const lowered = value.toLowerCase()
  for (const [name, code] of Object.entries(NATIONALITY_TO_COUNTRY_CODE)) {
    if (name.toLowerCase() === lowered) return code
  }
  return ""
}
